"""empty message

Revision ID: 01c0168ca4b0
Revises: d567cc0a7f85
Create Date: 2023-07-07 00:14:07.844284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c0168ca4b0'
down_revision = 'd567cc0a7f85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apartment_group_id_fkey', 'apartment', type_='foreignkey')
    op.drop_column('apartment', 'group_id')
    op.add_column('group', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('start_of_lease', sa.Date(), nullable=True))
    op.add_column('group', sa.Column('end_of_lease', sa.Date(), nullable=True))
    op.add_column('group', sa.Column('settlers_limit', sa.Integer(), nullable=False))
    op.add_column('group', sa.Column('description', sa.String(), nullable=True))
    op.add_column('group', sa.Column('title', sa.String(), nullable=False))
    op.create_foreign_key(None, 'group', 'apartment', ['apartment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'title')
    op.drop_column('group', 'description')
    op.drop_column('group', 'settlers_limit')
    op.drop_column('group', 'end_of_lease')
    op.drop_column('group', 'start_of_lease')
    op.drop_column('group', 'apartment_id')
    op.add_column('apartment', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('apartment_group_id_fkey', 'apartment', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
