"""Add AI to id

Revision ID: 6a841a336675
Revises: bfdff0fa9892
Create Date: 2023-06-20 13:02:40.014342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a841a336675'
down_revision = 'bfdff0fa9892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
