"""Clear db

Revision ID: bfdff0fa9892
Revises: d83b438559fd
Create Date: 2023-06-19 23:57:11.688493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfdff0fa9892'
down_revision = 'd83b438559fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('figi', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('instrument_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='operation_pkey')
                    )
    # ### end Alembic commands ###
