"""Update apartment models

Revision ID: d567cc0a7f85
Revises: 22688e7e9948
Create Date: 2023-07-02 13:32:22.742797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd567cc0a7f85'
down_revision = '22688e7e9948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('type', sa.String(), nullable=False))
    op.add_column('apartment', sa.Column('room_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'room_count')
    op.drop_column('apartment', 'type')
    # ### end Alembic commands ###
