"""Create table

Revision ID: d83b438559fd
Revises:
Create Date: 2023-06-19 21:52:52.228775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b438559fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('apartment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('price', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('groupUser',
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
                    )
    op.create_table('address',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('zip_code', sa.String(), nullable=False),
                    sa.Column('apartment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                                            ['apartment_id'],
                                            ['apartment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('operation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.String(), nullable=True),
                    sa.Column('figi', sa.String(), nullable=True),
                    sa.Column('instrument_type', sa.String(), nullable=True),
                    sa.Column('date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('address')
    op.drop_table('groupUser')
    op.drop_table('apartment')
    op.drop_table('group')
    # ### end Alembic commands ###
